### ISSUE TITLE
OBS Websocket integration

### ISSUE THREAD

**Issue by Khosumi** [KK964/SynthRiders-Websockets-Mod#1]
The required events for a functional OBS plugin is already there, such as song start and song end.
These could be used to start and stop a recording of the song, and then additionally use the existing tags to name a recorded file.

Additional tags could be considered such as active modifiers

**Comment by KK964** [comment]
The current use of the mod is just to act as a way to get info out of the game. If you want to be able to control OBS using the mod, I would recommend using [Streamer.bot](https://streamer.bot)
